package me.hoosiertransfer.caverntech.items;

import org.bukkit.Material;

import io.github.thebusybiscuit.slimefun4.api.items.SlimefunItemStack;
import io.github.thebusybiscuit.slimefun4.core.attributes.Radioactivity;
import io.github.thebusybiscuit.slimefun4.utils.LoreBuilder;

public class CavernTechItems {
    // Materials
    public static final SlimefunItemStack BORON_INGOT = new SlimefunItemStack("CAVERN_BORON_INGOT", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTlmMjMzMGFkMjg0NmVjNmM4ZTFjZTAyNTg5ZjA3ZjJmNzU5N2I1YTk3NzU5OWI2ZGI3YzM0NGNhNDRhMTI3NiJ9fX0", "硼锭", "&9&o洞穴科技");
    public static final SlimefunItemStack FERROBORON_INGOT = new SlimefunItemStack("CAVERN_FERROBORON_INGOT", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzllMzMzYTc2NGY4NzJjMDc4NmVkZTU3NTE4NDk1ODMzZGY0Y2EzZjdkNmQyZWJlYTdiMzIzZWY0OWFiNzg5YSJ9fX0", "硼铁合金锭", "&9&o洞穴科技");
    public static final SlimefunItemStack HARD_CARBON_ALLOY = new SlimefunItemStack("CAVERN_HARD_CARBON_ALLOY", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjg0OWM4NTYzYjQ5YzVjZDY1MDY2Yjg2N2U5OWVkYjI4NWRhOTVmMGZkMjEwZTIzZmEzNWI1YzVjNTg5MjEwNyJ9fX0", "硬碳合金", "&9&o洞穴科技");
    public static final SlimefunItemStack ELECTROLYTE_INGOT = new SlimefunItemStack("CAVERN_ELECTROLYTE_INGOT", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZWRkNzAxZDkyYjBjMjMwMmZkOTQwNWY0MzIyODliYzJlMGI0NDYxMDc0M2JjN2QyNTkxZGJhNzdiZjYzZDBmNCJ9fX0", "电解质锭", "", "&9&o洞穴科技");
    public static final SlimefunItemStack TOUGH_ALLOY = new SlimefunItemStack("CAVERN_TOUGH_ALLOY", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTg3MjVmMzQ5ZDAwY2Q2YjY5ZDYzYjU4YjRlYTNiZmY1Y2RlNWYxNDM1NjAyM2Q3MTUxYTNhNGEzMmRlNGI0YiJ9fX0", "韧性合金", "", "&9&o洞穴科技");
    public static final SlimefunItemStack EXTREME_ALLOY = new SlimefunItemStack("CAVERN_EXTREME_ALLOY", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDk4NmI5OGRlZDVmNjgzMjM1NDg5M2JiZWI0NzI1NjMzNWQzMmY0ZjZhZTE0OGY1MTQwY2IwOWUyYjI2YWM4MiJ9fX0", "极端合金", "", "&9&o洞穴科技");
    public static final SlimefunItemStack THERMOCONDUCTING_ALLOY = new SlimefunItemStack("CAVERN_THERMOCONDUCTING_ALLOY", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNWQyOTMwYzhiMGU2M2QxY2E2YTBhMDU4YTgzNjdmNGY2MDg4MTlmOTY4YmJhYWI0ZjAzY2YwMTNlNjJmZmMwMSJ9fX0", "导热合金", "", "&9&o洞穴科技");
    public static final SlimefunItemStack BISMUTH = new SlimefunItemStack("CAVERN_BISMUTH", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZGRjN2FiNGU3ZTRlZjI4ZmNiZTUxMzI3MTliNGEzNmY0ZjA1NmRkNzk0MWJjZTQwMGRmMzBjODU2NmI1ZGRlZCJ9fX0", "铋锭", "", "&9&o洞穴科技");
    public static final SlimefunItemStack PLATINUM = new SlimefunItemStack("CAVERN_PLATINUM", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTAyZjRhOWQxODJjYzYyNTkyNWU1ZGVhN2UyOWQxM2E5NDhhZDY0ZmY0Mjg3MTc4YWYyM2EwNDI4ZTFmYTU0ZSJ9fX0", "铂锭", "", "&9&o洞穴科技");
    public static final SlimefunItemStack SOULARIUM = new SlimefunItemStack("CAVERN_SOULARIUM", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzBlMWRhNTg2OTU0MjFkNDU1OGI3NzIyYmQ5OWU4ZjU3MGFmNDcyYWIxMDdmNTQxOTM4ZGI1MDRkNjQ3MmQwYiJ9fX0", "日光合金", "", "&9&o洞穴科技");
    public static final SlimefunItemStack BERYLLIUM_INGOT = new SlimefunItemStack("CAVERN_BERYLLIUM_INGOT", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTAyZjNkNTVhMjI0NWZkODMyOTJlZGU3MTA2NmFhOTYwMDJiNWU4N2VkZGU0ZTkzYjFhOTYwYTJkODE1ZTA0ZCJ9fX0", "铍锭", "", "&9&o洞穴科技");
    public static final SlimefunItemStack FLEXIUM_INGOT = new SlimefunItemStack("CAVERN_FLEXIUM_INGOT", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTQ4NjE3OTUyM2RjZWY2OWY1MTc1NmYxOGJjMGVlNWYzNGIyMTVlNDVlODMxM2I5YTNjOWNiYTdlZWI5MTRlMSJ9fX0", "柔性锭", "", "&9&o洞穴科技");
    public static final SlimefunItemStack RADIUM = new SlimefunItemStack("CAVERN_RADIUM", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDIwN2M1ZTc2NGM2MWMxNWNiOTdhYmI2MjA0Y2Q2ZjVmYzk2M2UwNzI2NGIxNDA0MzBkMzk3MmEyNzFhN2RhIn19fQ", "&a镭", "", LoreBuilder.radioactive(Radioactivity.HIGH), LoreBuilder.HAZMAT_SUIT_REQUIRED, "&9&o洞穴科技");
    public static final SlimefunItemStack EMPTY_RESERVOIR = new SlimefunItemStack("CAVERN_EMPTY_RESERVOIR", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNWYzOGY2OGI5MmUzYzU5YTgwMmFjMjNlM2IyY2U0ZTkyYjEzOGMxMTE4ZjI3OWI2ZTQwMDY2OTU4ZThmNzRmNyJ9fX0", "&b空储罐", "", "&7液体: &f空", "", "&9&o洞穴科技");
    public static final SlimefunItemStack WATER_RESERVOIR = new SlimefunItemStack("CAVERN_WATER_RESERVOIR", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvY2MyMmY2MTYwNjgzMjY1YjhmZWYxMTMzMTdjMThjZjQ0ZWRmMmEwNjZiNTZhOGM4ZmQzMjVmNmI5MjBhNWY4In19fQ", "&b储罐", "", "&7液体: &f水", "", "&9&o洞穴科技");
    public static final SlimefunItemStack LAVA_RESERVOIR = new SlimefunItemStack("CAVERN_LAVA_RESERVOIR", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTNlOTY4NTE1ODllMWZhODU0ZjA0ODRjMzBkNjM0ZmE0Njc0MDk2NmE2NmMwOTllMWM2NDIxOWMxMWNiYTdhNSJ9fX0", "&b储罐", "", "&7液体: &c岩浆", "", "&9&o洞穴科技");
    public static final SlimefunItemStack BISMUTHPLATES = new SlimefunItemStack("CAVERN_BISMUTHPLATES", Material.NETHERITE_SCRAP, "&l铋板", "", "&9&o洞穴科技");
    public static final SlimefunItemStack MACHINE_MOTOR = new SlimefunItemStack("CAVERN_MACHINE_MOTOR", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2IwNDMzZjFjMjI3OTYwOGY3YmQyY2VjZWI5OGNkMTc1Y2JhYWRjM2Y2Mjk5YWUzY2NhZTI1N2RjMjJhNTViMiJ9fX0", "&c机器马达", "&7机器组件", "", "&9&o洞穴科技");
    public static final SlimefunItemStack MACHINEPLATING = new SlimefunItemStack("CAVERN_MACHINEPLATING", Material.PAPER, "&b机械板", "&7机器组件", "", "&9&o洞穴科技");
    public static final SlimefunItemStack MACHINE_FRAME = new SlimefunItemStack("CAVERN_MACHINE_FRAME", Material.IRON_BLOCK, "&b机械框架", "&7机器组件", "", "&9&o洞穴科技");
    public static final SlimefunItemStack SOUL_FRAGMENT = new SlimefunItemStack("CAVERN_SOUL_FRAGMENT", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjIwMWFlMWE4YTA0ZGY1MjY1NmY1ZTQ4MTNlMWZiY2Y5Nzg3N2RiYmZiYzQyNjhkMDQzMTZkNmY5Zjc1MyJ9fX0", "灵魂碎片", "", "&9&o洞穴科技");
    public static final SlimefunItemStack REFINED_SOUL = new SlimefunItemStack("CAVERN_REFINED_SOUL", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzhjZWI4NjMxYWRkN2NiYjU2NWRjYjcwNWYxMjEyMzQ5Y2NjZDc1NTk2NWM0NmE5MjI4NTJjOWZkOTQ4YjRiYiJ9fX0", "精致的灵魂", "", "&9&o洞穴科技");
    // Machines
    public static final SlimefunItemStack PRESSURIZED_CARBON_PRESS = new SlimefunItemStack("CAVERN_PRESSURIZED_CARBON_PRESS", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjA5MTQyZjNhMGFiY2Y5YWZkYjkzYmNjZDdmNGQ3MzNjYzZlZTM0N2Y3NjBiNGE3Y2IzM2ZiZDljZjk5YWJiMCJ9fX0", "&e强化碳压机", "", "&7将原木压制成碳", "", LoreBuilder.power(200, "/t"), LoreBuilder.power(600, " 可储存"));
    public static final SlimefunItemStack SALT_PRODUCER = new SlimefunItemStack("CAVERN_SALT_PRODUCER", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTk0Y2M3MjVlM2VjNDJkOTc0NjQwNDMxODBiNmEyYTZiNmYwZGU4OGNkZjY0NmM2NDk0NTIwODM2YTQ4YThiNyJ9fX0", "&f制盐机", "",  LoreBuilder.power(32, "/t"), LoreBuilder.power(96, " 可储存"));
    public static final SlimefunItemStack CORRUPTER = new SlimefunItemStack("CAVERN_CORRUPTER", Material.GILDED_BLACKSTONE, "&c腐坏机", "",  "&7将方块破坏成不同的状态。", "", LoreBuilder.power(60, "/t"), LoreBuilder.power(180, " 可储存"));
    public static final SlimefunItemStack COBBLE_GEN = new SlimefunItemStack("CAVERN_COBBLE_GEN", Material.CHISELED_DEEPSLATE, "&8圆石生成器", "", "&7你认为它有什么作用?", "", LoreBuilder.power(48, "/t"), LoreBuilder.power(360, " 可储存"));
    public static final SlimefunItemStack INGOTEXTRACTOR = new SlimefunItemStack("CAVERN_INGOTEXTRACTOR", Material.FURNACE, "&8铸锭提取机", "&7将圆石转化为金属锭", "", LoreBuilder.speed(10), LoreBuilder.power(48, "/t"));
    public static final SlimefunItemStack SOUL_HARVESTER = new SlimefunItemStack("CAVERN_SOUL_HARVESTER", Material.BLACK_TERRACOTTA, "&5灵魂收割机", "", "&7每生产1个灵魂碎片", "&7需666秒");
}
